#!/usr/bin/env python3
"""gen_board_def.py — pinmap.yaml -> siot_board_def_gen.h (brief §2, siot_board_def).

Run by firmware/components/platform/siot_board_def/CMakeLists.txt at configure time:
    python3 gen_board_def.py pinmap.yaml <out_dir>/siot_board_def_gen.h
Requires PyYAML (present in the ESP-IDF python environment).
"""
import sys
from pathlib import Path

import yaml

PIN_FIELDS = ("led_r", "led_g", "led_b", "button", "acok", "uart0_tx", "uart0_rx", "usb_dm", "usb_dp")


def c_bool(v) -> str:
    return "true" if bool(v) else "false"


def main(argv):
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    src, dst = Path(argv[1]), Path(argv[2])
    doc = yaml.safe_load(src.read_text())
    if doc.get("schema") != 1:
        raise SystemExit(f"{src}: unsupported schema {doc.get('schema')!r}")
    boards = doc["boards"]
    defaults = [b for b in boards if b.get("default")]
    if len(defaults) != 1:
        raise SystemExit(f"{src}: exactly one board must have default: true (found {len(defaults)})")

    family_byte = {"board": 0x01, "node": 0x02, "leaf": 0x03}
    seen_codes = {}
    for b in boards:
        family = b.get("family", "node")
        code = b.get("code")
        if not isinstance(code, int) or not 0x0100 <= code <= 0x03FF:
            raise SystemExit(f"{src}: board {b['model']} needs code: 0xFFPP (family byte, product byte)")
        if family in family_byte and (code >> 8) != family_byte[family]:
            raise SystemExit(f"{src}: board {b['model']}: code {code:#06x} does not start with "
                             f"the {family} family byte {family_byte[family]:#04x}")
        if code in seen_codes and seen_codes[code] != b["model"]:
            raise SystemExit(f"{src}: code {code:#06x} is used by {seen_codes[code]} and {b['model']}")
        seen_codes[code] = b["model"]

    lines = [
        "/* Generated by tools/pinmap/gen_board_def.py from tools/pinmap/pinmap.yaml. Do not edit. */",
        "#pragma once",
        "#include \"siot_board_def.h\"",
        "",
        f"#define SIOT_BOARD_DEF_COUNT {len(boards)}",
        "",
        "static const siot_board_def_t SIOT_BOARD_DEFS[SIOT_BOARD_DEF_COUNT] = {",
    ]
    for b in boards:
        pins = b["pins"]
        for f in PIN_FIELDS:
            if f not in pins:
                raise SystemExit(f"{src}: board {b['model']} lacks pin {f}")
        lines.append("    {")
        lines.append(f"        .model = \"{b['model']}\",")
        family = b.get("family", "node")
        if family not in ("board", "node", "leaf"):
            raise SystemExit(f"{src}: board {b['model']} has unknown family {family!r}")
        lines.append(f"        .family = \"{family}\",")
        lines.append(f"        .product = 0x{int(b['code']):04X},")
        lines.append(f"        .hw_rev = {int(b.get('hw_rev', 0))},")
        lines.append(f"        .is_default = {c_bool(b.get('default', False))},")
        for f in PIN_FIELDS:
            lines.append(f"        .{f} = {int(pins[f])},")
        lines.append(f"        .led_active_low = {c_bool(pins.get('led_active_low', False))},")
        lines.append("    },")
    lines += ["};", ""]
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
