/// Response of GET /info on the device's SoftAP (192.168.4.1) —
/// POC-BRIEF.md §5. `nonce` is regenerated by the device on every call and
/// is the input to both /identify's proof and /provision's key derivation.
class DeviceApInfo {
  final String id;
  final String mac;
  final String model;
  final String fw;
  final String state;
  final String nonceHex;

  const DeviceApInfo({
    required this.id,
    required this.mac,
    required this.model,
    required this.fw,
    required this.state,
    required this.nonceHex,
  });

  factory DeviceApInfo.fromMap(Map<String, dynamic> map) => DeviceApInfo(
        id: map['id'] as String? ?? '',
        mac: map['mac'] as String? ?? '',
        model: map['model'] as String? ?? '',
        fw: map['fw'] as String? ?? '',
        state: map['state'] as String? ?? 'idle',
        nonceHex: map['nonce'] as String? ?? '',
      );
}

/// Response of GET /status while the device stores/joins (POC-BRIEF §5).
/// state: idle | identified | stored | joining | online | failed
class DeviceApStatus {
  final String state;
  final String? detail;

  const DeviceApStatus({required this.state, this.detail});

  factory DeviceApStatus.fromMap(Map<String, dynamic> map) => DeviceApStatus(
        state: map['state'] as String? ?? 'idle',
        detail: map['detail'] as String?,
      );
}
