import '../../../central/domain/safr/safr_product.dart';

/// Response of GET /info on the device's SoftAP (192.168.4.1) —
/// POC-BRIEF.md §5. `nonce` is regenerated by the device on every call and
/// is the input to both /identify's proof and /provision's key derivation.
class DeviceApInfo {
  final String id;
  final String mac;
  final String model;
  final String fw;
  final String state;
  final String nonceHex;

  /// The unit's PRODUCT code (reference §2.1, protocol §7.11): what it is.
  /// Null on firmware that does not report it, or when it reports 0.
  final int? productCode;

  /// PCB revision; null when not reported or not stated (0).
  final int? hwRev;

  /// What the unit is: from the code it reports, else from its model string
  /// (older firmware); null when neither is in the catalogue.
  SafrProduct? get product =>
      SafrProduct.fromCode(productCode) ?? SafrProduct.fromModel(model);

  /// "Sirene · SIOT-SIREN-01"; the bare model when it is not in the
  /// catalogue; "—" when the unit reported nothing.
  String get productDisplay =>
      product?.display ?? (model.isEmpty ? '—' : model);

  const DeviceApInfo({
    required this.id,
    required this.mac,
    required this.model,
    required this.fw,
    required this.state,
    required this.nonceHex,
    this.productCode,
    this.hwRev,
  });

  factory DeviceApInfo.fromMap(Map<String, dynamic> map) => DeviceApInfo(
        id: map['id'] as String? ?? '',
        mac: map['mac'] as String? ?? '',
        model: map['model'] as String? ?? '',
        fw: map['fw'] as String? ?? '',
        state: map['state'] as String? ?? 'idle',
        nonceHex: map['nonce'] as String? ?? '',
        productCode: _positive(map['product']),
        hwRev: _positive(map['hw_rev']),
      );

  static int? _positive(Object? v) => v is num && v > 0 ? v.toInt() : null;
}

/// Response of GET /status while the device stores/joins (POC-BRIEF §5).
/// state: idle | identified | stored | joining | online | failed
class DeviceApStatus {
  final String state;
  final String? detail;

  const DeviceApStatus({required this.state, this.detail});

  factory DeviceApStatus.fromMap(Map<String, dynamic> map) => DeviceApStatus(
        state: map['state'] as String? ?? 'idle',
        detail: map['detail'] as String?,
      );
}
