# siot_signing.cmake — stage-1 app signing for every product image (OTA brief
# decision 8, docs/ota/signing-key.md). Included by apps/<app>/CMakeLists.txt
# BEFORE project.cmake.
#
# The private key is never in the repository. It is looked up in this order:
#   1. the environment variable SIOT_SIGNING_KEY (a path to the .pem)
#   2. ~/.sempreiot/keys/sempreiot_dev_signing_key.pem (the development key)
# The path found is written, absolute, into a small sdkconfig fragment in the
# build directory and appended to SDKCONFIG_DEFAULTS, so `idf.py build` and
# firmware/build.sh behave the same and no path is ever typed into a versioned
# file.
#
# No key: the build STOPS and says how to get one. SIOT_UNSIGNED=1 in the
# environment builds an unsigned image instead — for a bench unit flashed by
# cable only; a unit running a signed image refuses it over OTA.
#
# Symbols checked in $IDF_PATH/components/bootloader/Kconfig.projbuild (v5.5.2):
# SECURE_SIGNED_APPS_NO_SECURE_BOOT, SECURE_SIGNED_APPS_RSA_SCHEME (the only
# scheme on ESP32-S3), SECURE_SIGNED_ON_UPDATE_NO_SECURE_BOOT,
# SECURE_BOOT_BUILD_SIGNED_BINARIES, SECURE_BOOT_SIGNING_KEY.

if(NOT SDKCONFIG_DEFAULTS)
    set(SDKCONFIG_DEFAULTS "sdkconfig.defaults")
endif()

set(_siot_fragment "${CMAKE_BINARY_DIR}/sdkconfig.signing")

if("$ENV{SIOT_UNSIGNED}" STREQUAL "1")
    message(WARNING "SIOT_UNSIGNED=1: building an UNSIGNED image. Units that run a signed image "
                    "will refuse it over OTA. Never release this build.")
    file(WRITE "${_siot_fragment}" "# SIOT_UNSIGNED=1\n# CONFIG_SECURE_SIGNED_APPS_NO_SECURE_BOOT is not set\n")
else()
    if(DEFINED ENV{SIOT_SIGNING_KEY} AND NOT "$ENV{SIOT_SIGNING_KEY}" STREQUAL "")
        set(_siot_key "$ENV{SIOT_SIGNING_KEY}")
    else()
        set(_siot_key "$ENV{HOME}/.sempreiot/keys/sempreiot_dev_signing_key.pem")
    endif()
    get_filename_component(_siot_key "${_siot_key}" ABSOLUTE)
    if(NOT EXISTS "${_siot_key}")
        message(FATAL_ERROR
            "\nNo firmware signing key at ${_siot_key}\n"
            "Every SempreIoT image is signed (docs/ota/signing-key.md). Either\n"
            "  - copy the team's key to that path (chmod 600), or point SIOT_SIGNING_KEY at it, or\n"
            "  - make a new development key:  firmware/tools/signing_key.sh new\n"
            "    (units signed with another key must then be flashed by cable once), or\n"
            "  - build unsigned for a cable-flashed bench unit:  SIOT_UNSIGNED=1 idf.py build\n")
    endif()
    file(WRITE "${_siot_fragment}"
"# Generated by firmware/tools/cmake/siot_signing.cmake — do not edit, do not commit.
CONFIG_SECURE_SIGNED_APPS_NO_SECURE_BOOT=y
CONFIG_SECURE_SIGNED_APPS_RSA_SCHEME=y
CONFIG_SECURE_SIGNED_ON_UPDATE_NO_SECURE_BOOT=y
CONFIG_SECURE_BOOT_BUILD_SIGNED_BINARIES=y
CONFIG_SECURE_BOOT_SIGNING_KEY=\"${_siot_key}\"
")
    message(STATUS "SempreIoT: images signed with ${_siot_key}")
endif()

list(APPEND SDKCONFIG_DEFAULTS "${_siot_fragment}")
