// GENERATED by tool/blender/model_factory.py from tool/blender/models.json
// and the product catalogue (docs/sempreiot-system-reference.md §2.1).
// Do not edit: change the manifest and run tool/blender/factory.sh.

import '../../../domain/safr/safr_product.dart';
import 'device_model_sprites.dart';

/// Every device model the app can draw.
const deviceModelSpecs = <DeviceModelSpec>[
  DeviceModelSpec(
    slug: 'smoke_detector',
    productCodes: [0x0301], // SIOT-SMOKE-01
    familyFallback: SafrProductFamily.leaf,
    atlas: 'assets/models/smoke_detector_atlas.png',
    spin: 'assets/models/smoke_detector_spin.png',
    glow: null,
    spinGlow: null,
    frames: 'assets/models/smoke_detector_frames.json',
    displaySize: 52.0,
    alarmSound: false,
  ),
  DeviceModelSpec(
    slug: 'siren',
    productCodes: [0x0201], // SIOT-SIREN-01
    familyFallback: null,
    atlas: 'assets/models/siren_atlas.png',
    spin: 'assets/models/siren_spin.png',
    glow: 'assets/models/siren_glow.png',
    spinGlow: 'assets/models/siren_spin_glow.png',
    frames: 'assets/models/siren_frames.json',
    displaySize: 56.0,
    alarmSound: true,
  ),
  DeviceModelSpec(
    slug: 'push_button',
    productCodes: [0x0202], // SIOT-PBS-01
    familyFallback: null,
    atlas: 'assets/models/push_button_atlas.png',
    spin: 'assets/models/push_button_spin.png',
    glow: null,
    spinGlow: null,
    frames: 'assets/models/push_button_frames.json',
    displaySize: 52.0,
    alarmSound: false,
  ),
];
